<script>
	import '@fontsource/urbanist';
	import '../app.css';
	import PromotionBar from '$lib/components/PromotionBar/index.svelte';
	import Header from '$lib/components/layout/Header/index.svelte';
</script>

<svelte:head>
	<title>FameTonic</title>
	<meta name="description" content="Generated by create svelte app" />
</svelte:head>

<div class="flex flex-col min-h-screen font-urbanist">
	<PromotionBar />
	<Header />
	<div class="flex justify-center">
		<main class="flex-grow max-w-[1536px] relative">
			<slot />
		</main>
	</div>
</div> 